on:
  push:
  workflow_dispatch:
jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan
        id: terrascan
        uses: docker://nasirrabbani/terrascan-action:test3
        with:
          only_warn: true
          verbose: true
          notification_webhook_url: https://b8ff-103-83-214-125.ngrok.io/v1/api/terrascan
          notification_webhook_token: 69c5976d-f134-433d-bc66-8567a4b5511b
          repo_url: https://github.com/test-org-pankaj/miniature-funicular.git